### ISSUE TITLE
Not able to figure out value for Converter ratio?

### ISSUE THREAD

**Issue by Neel7391** [hilch/demo-AP3131#1]
Hello Dear;
I am using your code to read the values from AP3131 card, Everything is working fine but the Irms values seems not be correct 

I am using CT 100A/5A to measure the current but I am not sure what values I should set for I_ratioA and Converter ratio

providing following data
converterRatio := 100/5; (As I am using current transformer 100A to 5A)
I_Ratio=100
apData.CfgAct.I_RatioA = 18334
**Rms.IrmsA = 36.64** "(UINT_TO_REAL(apData.Rms.IrmsA) * currentCorrectionFactor / 1000.0)"

But I am not getting the correct value as actual value supplied is 64A 

can you help me to identify the error?

**Comment by hilch** [comment]
Hi,
well, AP3131 is designed for i primary = 65A max. Since module's max. input current is 5 Amps a maximum transformation ratio of  13 can be used (see GUID 29b656b9-d9e0-43b8-82ae-be4f81faa877). 
You use a transformation ratio of 50 so we need a 'hack':

64 Amps primary results in 3.2A secondary which will be shown as 32A by setting I_RatioA to 100 (default).
Since this is wrong it has to be corrected outside the module:

currentCorrectionFactor := converterRatio / (UINT_TO_LREAL(apData.CfgAct.I_RatioA) / 10);

currentCorrectionFactor = 100/5 / (  100 / 10 ) = 2

**Comment by Neel7391** [comment]
Hey thank you so much for the reply. But what hack should I use to make it correct?
can you please help me to give sample code with bit clear example?

**Comment by hilch** [comment]
It looks like you already did the hack: set all 'Phase X current ratio' in hardware tree to '100' and 
in CondMon.st / PROGRAM _INIT:  converterRatio := 100/5;

Honestly the content of your I_RatioA register looks weired. Unfortunately I currently have no access to hardware to check if DataType X20AP31X needs to be adapted in newer versions of AS so there is no quick solution available from my side.
I recommend to contact your local B&R Office if this still doesn't work for you.

**Comment by Neel7391** [comment]
Actually the content of IratioA is 100 in above comment it was typo mistake instead the value of apData.Rms.IrmsA= 18334 at 65A, And for your information I have done the same kept 100 in HW configuration and converterRatio := 100/5; but still its not

**Comment by hilch** [comment]
your settings are ok. Then you should measure 3.25 Amps at converter's output with a multimeter. The module 'believes to see' 1.83 Amps since the ratio set in the module is 10.0 now (18.334 Amps / 10.0).

**Comment by Neel7391** [comment]
Hey.. We have tried with 60A/5A CT and it worked perfectly fine but not with 100A CT.. Thank you..
